<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>pe.finaciera.bs.pagoservicios</groupId>
    <artifactId>bspagoservicios</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    <name>bspagoservicios</name>
    <description>bspagoservicios microservice</description>

    <properties>
        <java.version>21</java.version>
        <dependency.lombok.version>1.18.36</dependency.lombok.version>
        <dependency.flyway.version>10.20.0</dependency.flyway.version>
        <dependency.springdoc.version>2.8.5</dependency.springdoc.version>
        <dependency.gson.version>2.11.0</dependency.gson.version>
        <dependency.pub-sub.version>1.8.1</dependency.pub-sub.version>
        <dependency.common.version>1.6.0</dependency.common.version>
        <dependency.redisson.version>3.38.1</dependency.redisson.version>
        <postgresql.version>42.7.11</postgresql.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${dependency.lombok.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>${dependency.flyway.version}</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <version>${dependency.flyway.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${dependency.gson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${dependency.springdoc.version}</version>
        </dependency>
        <dependency>
            <groupId>financieraoh-framework</groupId>
            <artifactId>pub-sub</artifactId>
            <version>${dependency.pub-sub.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>financieraoh-framework</groupId>
            <artifactId>common</artifactId>
            <version>${dependency.common.version}</version>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>${dependency.redisson.version}</version>
        </dependency>
        <dependency>
            <groupId>framework</groupId>
            <artifactId>framework-logging</artifactId>
            <version>0.6.1-1</version>
        </dependency>
        <dependency>
            <groupId>framework</groupId>
            <artifactId>framework-metrics</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>financieraoh-framework</groupId>
            <artifactId>framework-testing</artifactId>
            <version>1.1.0-RELEASE</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>financieraoh-framework</groupId>
            <artifactId>auditoria</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-parameter-names</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>framework-arquitectura</id>
            <url>https://pkgs.dev.azure.com/financieraoh/Banking-Microservices/_packaging/framework-arquitectura/maven/v1</url>
        </repository>
    </repositories>
    <distributionManagement>
        <repository>
            <uniqueVersion>false</uniqueVersion>
            <id>framework-arquitectura</id>
            <name>framework-arquitectura</name>
            <url>https://pkgs.dev.azure.com/financieraoh/Banking-Microservices/_packaging/framework-arquitectura/maven/v1</url>
            <layout>default</layout>
        </repository>
    </distributionManagement>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.rabbitmq</groupId>
                <artifactId>amqp-client</artifactId>
                <version>5.33.1</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.6.3</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>1.6.3</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-utils</artifactId>
                <version>3.6.1</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven.shared</groupId>
                <artifactId>maven-shared-utils</artifactId>
                <version>3.3.3</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-core</artifactId>
                <version>3.8.1</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-compat</artifactId>
                <version>3.8.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <compilerArgs>
                        <arg>--release</arg>
                        <arg>21</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <!-- Plugins to run Unit Tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <argLine>${surefireArgLine}</argLine>
                    <skipTests>${skip.unit.tests}</skipTests>
                    <excludes>
                        <exclude>**/MainApplication*</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <propertyName>surefireArgLine</propertyName>
                        </configuration>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <title>Reporte de cobertura del proyecto</title>
                            <excludes>
                                <exclude>**/MainApplication*</exclude>
                                <exclude>**/config/**</exclude>
                                <exclude>**/entity/**</exclude>
                                <exclude>**/constant/**</exclude>
                                <exclude>**/domain/**</exclude>
                                <exclude>**/event/**</exclude>
                                <exclude>**/mapper/**</exclude>
                                <exclude>**/advice/**</exclude>
                                <exclude>**/request/**</exclude>
                                <exclude>**/response/**</exclude>
                                <exclude>**/repository/**</exclude>
                                <exclude>**/exception/**</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>**/MainApplication*</exclude>
                                <exclude>**/config/**</exclude>
                                <exclude>**/entity/**</exclude>
                                <exclude>**/constant/**</exclude>
                                <exclude>**/domain/**</exclude>
                                <exclude>**/event/**</exclude>
                                <exclude>**/mapper/**</exclude>
                                <exclude>**/advice/**</exclude>
                                <exclude>**/request/**</exclude>
                                <exclude>**/response/**</exclude>
                                <exclude>**/repository/**</exclude>
                                <exclude>**/exception/**</exclude>
                            </excludes>
                            <rules>
                                <rule>
                                    <element>PACKAGE</element>
                                    <limits>
                                        <limit>
                                            <counter>LINE</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.8</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
