# Application definition
appName: bspagoservicios

# Deployment & Server values
server:
  port: 8080
  servlet:
    context-path: /bspagoservicios
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: bspagoservicios
  jmx:
    enabled: true
  rabbitmq:
    username: ${RABBITMQ_TRANSACTION_USR}
    password: ${RABBITMQ_TRANSACTION_PWD}
    host: ${RABBITMQ_TRANSACTION_HOST}
    port: ${RABBITMQ_TRANSACTION_PORT}
  datasource:
    url: ${BD_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    hikari:
      idle-timeout: 60000
      login-timeout: 3
      max-lifetime: 3600000
      minimum-idle: 2
      validation-timeout: 3000
      initialization-fail-timeout: 5
      connection-timeout: 10000
      maximum-pool-size: 10
  jpa:
    show-sql: false
    flyway:
      enabled: true
      schemas: ecatalogo
      default-schema: ecatalogo
      locations: classpath:db/migration
      baselineOnMigrate: true
    hibernate:
      ddl-auto: "none"
      default_schema: "ecatalogo"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true
      hibernate.order_updates: true
  jdbc:
    template:
      fetch-size: 10
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
  packages-to-scan: pe.financiera.bs.pagoservicios

logbook:
  format.style: json
  include[0]: '**/v1/**'
  exclude[0]: '**/v2/api-docs'
  exclude[1]: '**/swagger-ui/index.html'
  exclude[2]: '**/webjars/**'
  exclude[3]: '**/swagger-resources/**'
  exclude[4]: '**/csrf'
  exclude[5]: '**/'
  exclude[6]: '**/error'
  exclude[7]: '**/actuator/**'
  filter.enabled: true
  secure-filter.enabled: true
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    level: INFO
    category: elk-data
    max-body-size: 100

framework:
  logging:
    output: ${LOG_OUTPUT_SERVICE}
    level: ${LOG_LEVEL_SERVICE}
  auditoria:
    queue: ${AUDITORIA_QUEUE}
    exchange: ${AUDITORIA_EXCHANGE}
    routingKey: ${AUDITORIA_ROUTINGKEY}

# GCP configuration
gcp:
  credentials: ${GCP_CREDENTIALS}
  project-id: ${GCP_PROJECT_ID}

# Redis values
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

management:
  health:
    rabbit:
      enabled: false
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: bspagoservicios

# Integrations (services-api)
services-api:
  core:
    operation:
      base-url: ${MSC_OPERATION}
      connect-timeout: ${SERVICES_API_CORE_OPERATION_CONNECT_TIMEOUT}
      read-timeout: ${SERVICES_API_CORE_OPERATION_READ_TIMEOUT}
      write-timeout: ${SERVICES_API_CORE_OPERATION_WRITE_TIMEOUT}
      max-request: 100
      logEnabled: true
  gateway:
    interbank:
      base-url: ${MSG_INTERBANK}
      connect-timeout: ${SERVICES_API_GATEWAY_INTERBANK_CONNECT_TIMEOUT}
      read-timeout: ${SERVICES_API_GATEWAY_INTERBANK_READ_TIMEOUT}
      write-timeout: ${SERVICES_API_GATEWAY_INTERBANK_WRITE_TIMEOUT}
      max-request: 100
      logEnabled: true
  ux:
    home:
      base-url: ${UX_HOME_SERVICE}
      connect-timeout: ${SERVICES_UX_HOME_SERVICE_CONNECT_TIMEOUT}
      read-timeout: ${SERVICES_UX_HOME_SERVICE_READ_TIMEOUT}
      write-timeout: ${SERVICES_UX_HOME_SERVICE_WRITE_TIMEOUT}
      max-request: 100
      logEnabled: true
  bs:
    trxohpay:
      base-url: ${MSN_TRX_OHPAY}
      connect-timeout: ${SERVICES_API_BS_TRXOHPAY_CONNECT_TIMEOUT}
      read-timeout: ${SERVICES_API_BS_TRXOHPAY_READ_TIMEOUT}
      write-timeout: ${SERVICES_API_BS_TRXOHPAY_WRITE_TIMEOUT}
      max-request: 100
      logEnabled: true
    producto:
      base-url: ${MSN_PRODUCTOS}
      connect-timeout: ${SERVICES_API_BS_TRXOHPAY_CONNECT_TIMEOUT}
      read-timeout: ${SERVICES_API_BS_TRXOHPAY_READ_TIMEOUT}
      write-timeout: ${SERVICES_API_BS_TRXOHPAY_WRITE_TIMEOUT}
      max-request: 100
      logEnabled: true

# Queue values
queue:
  sp:
    bill:
      completed:
        v2:
          subscription:
            name: service-payment-bill-completed-v2-subscription
            max-ack-extension-period: ${BILL_COMPLETED_ACK_EXTENSION}
            deduplication-lock-ttl: ${BILL_COMPLETED_LOCK_TTL}
            key-ttl: ${BILL_COMPLETED_KEY_TTL}
            max-retries: ${BILL_COMPLETED_MAX_RETRY}
  subscription:
    deduplication-lock-ttl: 30
  dead:
    letter:
      publish:
        name: event-messaging-dead-letter-queue-publish
  publish:
    incorporate-started: incorporate-started-publish
